<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Isekai.Worker-740a260f-149f-47ea-92ca-7fabc03c696f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.5.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    </ItemGroup>
</Project>
